# -*- coding: utf-8 -*-
"""
generate_static_dashboard.py  (V3)
====================================
Copies pre-generated dashboard_data.json to docs/assets/
and verifies that all required static files exist.

The JSON is generated by build_strategy_layer.py (via export_public_dashboard_data).
This script is the final step — it just ensures docs/ is ready for GitHub Pages.

Build order:
  1. python src/build_network_heatmap.py
  2. python src/build_strategy_layer.py       ← generates JSON
  3. python src/generate_static_dashboard.py  ← copies + verifies
  4. python src/privacy_check.py              ← validates

Production URL:
  https://mauricio1806.github.io/Conections-map/
"""

import json
import logging
import shutil
import sys
import time
from pathlib import Path

# ── UTF-8 stdout on Windows ──────────────────────────────────────────────────
if hasattr(sys.stdout, "buffer"):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT        = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = ROOT / "outputs"
DOCS_DIR    = ROOT / "docs"
ASSETS_DIR  = DOCS_DIR / "assets"

SRC_JSON    = OUTPUTS_DIR / "public_dashboard_data.json"
DST_JSON    = ASSETS_DIR  / "dashboard_data.json"
INDEX_HTML  = DOCS_DIR    / "index.html"
STYLE_CSS   = ASSETS_DIR  / "style.css"
APP_JS      = ASSETS_DIR  / "app.js"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

REQUIRED_FILES = [INDEX_HTML, DST_JSON, STYLE_CSS, APP_JS]


def _check_json_sanity(path: Path) -> dict:
    """Basic sanity check on the dashboard JSON."""
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    kpis     = data.get("kpis", {})
    contacts = data.get("top_contacts", [])
    issues   = []

    # Check key V3 scores exist
    for key in ["strategic_network_score", "usd_readiness_score", "spain_eu_readiness_score"]:
        if key not in kpis:
            issues.append(f"Missing KPI: {key}")

    # Privacy check
    for i, c in enumerate(contacts[:10]):
        for field in c:
            if "email" in field.lower() or "phone" in field.lower():
                issues.append(f"PII field in contact #{i+1}: {field}")

    return {"kpis": kpis, "contacts": len(contacts), "issues": issues}


def _inject_cache_bust(build_ts: str) -> None:
    """Replace __BUILD_TS__ sentinel in app.js and add ?v= to HTML asset references."""
    # app.js: replace sentinel in DATA_PATHS
    app_text = APP_JS.read_text(encoding="utf-8")
    app_text = app_text.replace("'__BUILD_TS__'", "'" + build_ts + "'")
    APP_JS.write_text(app_text, encoding="utf-8")

    # index.html: stamp ?v=<ts> onto style.css and app.js references
    html_text = INDEX_HTML.read_text(encoding="utf-8")
    import re
    html_text = re.sub(r'(assets/style\.css)(\?v=[^"\']*)?', r'assets/style.css?v=' + build_ts, html_text)
    html_text = re.sub(r'(assets/app\.js)(\?v=[^"\']*)?',   r'assets/app.js?v='   + build_ts, html_text)
    INDEX_HTML.write_text(html_text, encoding="utf-8")
    logger.info(f"  Cache-bust timestamp injected: {build_ts}")


def main():
    logger.info("=" * 60)
    logger.info("  Generating Static HTML Dashboard (V3)")
    logger.info("=" * 60)
    logger.info(f"  Production URL: https://mauricio1806.github.io/Conections-map/")

    build_ts = str(int(time.time()))

    # Ensure docs/assets/ exists
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # Step 1: Copy dashboard_data.json to docs/assets/
    logger.info("Step 1/4: Copying dashboard_data.json to docs/assets/ ...")
    if not SRC_JSON.exists():
        logger.error(f"Source JSON not found: {SRC_JSON}")
        logger.error("Run `python src/build_strategy_layer.py` first.")
        sys.exit(1)

    shutil.copy2(SRC_JSON, DST_JSON)
    logger.info(f"  Copied: {SRC_JSON.name} → docs/assets/ ({DST_JSON.stat().st_size // 1024}KB)")

    # Step 1b: Inject cache-bust timestamp
    _inject_cache_bust(build_ts)

    # Step 2: Sanity check the JSON
    logger.info("Step 2/4: Validating dashboard_data.json ...")
    try:
        info = _check_json_sanity(DST_JSON)
        kpis = info["kpis"]
        logger.info(f"  Total connections:       {kpis.get('total_connections', '?')}")
        logger.info(f"  Strategic Network Score: {kpis.get('strategic_network_score', '?')}/100 ({kpis.get('strategic_network_level', '?')})")
        logger.info(f"  USD Readiness:           {kpis.get('usd_readiness_score', '?')}/100 ({kpis.get('usd_readiness_level', '?')})")
        logger.info(f"  Spain/EU Readiness:      {kpis.get('spain_eu_readiness_score', '?')}/100 ({kpis.get('spain_eu_readiness_level', '?')})")
        logger.info(f"  Market Confidence:       {kpis.get('market_confidence_score', '?')}/100")
        logger.info(f"  Unknown %:               {kpis.get('unknown_pct', '?')}%")
        logger.info(f"  Top contacts:            {info['contacts']}")
        if info["issues"]:
            for issue in info["issues"]:
                logger.warning(f"  [WARN] {issue}")
        else:
            logger.info("  JSON sanity check PASSED")
    except Exception as e:
        logger.warning(f"  JSON validation failed (non-fatal): {e}")

    # Step 3: Verify all required files exist
    logger.info("Step 3/4: Verifying all static files ...")
    all_ok = True
    for f in REQUIRED_FILES:
        if f.exists():
            logger.info(f"  [OK] {f.relative_to(ROOT)} ({f.stat().st_size // 1024}KB)")
        else:
            logger.error(f"  [MISSING] {f.relative_to(ROOT)}")
            all_ok = False

    if not all_ok:
        logger.error("Some required files are missing. Check the docs/ directory.")
        sys.exit(1)

    # Step 4: JS syntax check if node available
    logger.info("Step 4/4: JavaScript syntax check ...")
    import subprocess
    try:
        result = subprocess.run(
            ["node", "--check", str(APP_JS)],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            logger.info("  app.js syntax: OK")
        else:
            logger.error(f"  app.js SYNTAX ERROR:\n{result.stderr.strip()}")
            sys.exit(1)
    except FileNotFoundError:
        logger.info("  node not found — skipping JS syntax check")
    except Exception as e:
        logger.warning(f"  JS syntax check failed: {e}")

    logger.info("")
    logger.info("=" * 60)
    logger.info("  Static dashboard generation COMPLETE")
    logger.info(f"  Build timestamp: {build_ts}")
    logger.info("  Production: https://mauricio1806.github.io/Conections-map/")
    logger.info("  Local test: python -m http.server --directory docs")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
