# -*- coding: utf-8 -*-
"""
outreach_adjusted_scoring.py
=============================
Computes outreach_adjusted_score per contact, based on LinkedIn message history.

Reads outputs/message_threads_summary.csv (generated by lead_reactivation_engine).
Returns a dict keyed by normalized profile URL for fast O(1) lookup in export.

Scoring rules (additive, clamped 0–100):
  Base: connection priority_score * 0.40 (max 40 pts)
  Boost:
    +20  real reply (substantive, non-auto, messages_from_other >= 1)
    +25  CV/resume requested
    +30  interview/screening discussed
    +20  job/opportunity shared in conversation
    +15  positive opportunity signal (any)
    +10  recruiter/TA persona and they replied
    +10  warm dormant lead
    +10  last sender is them (I need to reply)
  Penalty:
    -30  ghosted — I sent, never replied, 14+ days ago
    -20  auto-reply only
    -15  career site redirect only
    -25  rejection/closed process, no reusable signal
    -10  older than 180 days, no positive signal
    -40  low value / ignore
  Clamp to [0, 100].

Outreach status labels (shown in dashboard):
  "Needs Reply" — they sent last, I haven't replied
  "Interview Pipeline" — interview/call discussed
  "CV Submitted / Follow-up" — CV sent/requested
  "Warm Lead" — positive signal, mutual exchange
  "Follow-up Due" — I sent, has opportunity, 7-120 days
  "Ghosted" — no response from them, 14+ days
  "Auto-reply Only" — no real human response
  "Rejected" — rejection signal
  "Dormant" — warm but > 30 days old
  "No History" — not in message data
"""

import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

ROOT        = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = ROOT / "outputs"
THREADS_CSV = OUTPUTS_DIR / "message_threads_summary.csv"

RECRUITER_PERSONAS = {
    "Recruiter", "Talent Acquisition", "Sourcer",
    "Hiring Manager", "Engineering Manager",
    "Data Engineering Manager", "Head of Data", "Director", "Executive",
}


def _norm_url(url: str) -> str:
    if not url:
        return ""
    return str(url).strip().rstrip("/").lower()


def _score_one(row: dict, base_score: float) -> tuple[int, str, str]:
    """Return (outreach_adjusted_score, outreach_status, outreach_reason)."""
    status           = str(row.get("conversation_status", "") or "")
    temperature      = str(row.get("lead_temperature", "") or "")
    persona          = str(row.get("persona", "") or "")
    has_positive     = bool(row.get("has_positive_signal", False))
    has_cv           = bool(row.get("has_cv_signal", False))
    has_interview    = bool(row.get("has_interview_signal", False))
    is_auto          = bool(row.get("is_auto_reply", False))
    msgs_from_other  = int(row.get("messages_from_other_person", 0) or 0)
    days_since       = int(row.get("days_since_last_message", 9999) or 9999)
    last_sender      = str(row.get("last_sender", "") or "")

    other_replied    = msgs_from_other > 0
    has_opp          = has_positive or has_cv or has_interview
    is_recruiter     = persona in RECRUITER_PERSONAS
    ghosted          = (last_sender == "me" and msgs_from_other == 0 and days_since >= 14)
    is_dormant       = (status == "Dormant warm lead")
    is_rejection     = (status == "Rejected / closed process")
    is_career_site   = (status == "Auto-reply / career site redirect")
    is_needs_reply   = (status == "Needs my response")
    is_follow_up     = (status == "Follow-up due")
    is_warm          = (status == "Warm lead")
    is_low_value     = (status == "Low value / ignore")

    # Base: 40% of connection priority score
    score = base_score * 0.40

    # Boosts
    if is_needs_reply:                  score += 10
    if other_replied and not is_auto:   score += 20
    if has_cv:                          score += 25
    if has_interview:                   score += 30
    if has_opp and not has_cv and not has_interview: score += 15
    if is_recruiter and other_replied:  score += 10
    if is_dormant:                      score += 10

    # Penalties
    if ghosted:                                     score -= 30
    if is_auto and not has_opp:                     score -= 20
    if is_career_site and not has_opp:              score -= 15
    if is_rejection:                                score -= 25
    if days_since > 180 and not has_opp:            score -= 10
    if is_low_value:                                score -= 40

    score = max(0, min(100, int(score)))

    # Outreach status label — driven by conversation_status (strict), not raw keywords
    if is_needs_reply:
        out_status = "Needs Reply"
    elif is_rejection:
        out_status = "Rejected"
    elif is_career_site:
        out_status = "Auto-reply"
    elif ghosted:
        out_status = "Ghosted"
    elif is_follow_up and has_interview:
        out_status = "Interview Pipeline"
    elif is_follow_up and has_cv:
        out_status = "CV / Follow-up"
    elif is_follow_up:
        out_status = "Follow-up Due"
    elif is_warm:
        out_status = "Warm Lead"
    elif is_dormant:
        out_status = "Dormant"
    elif other_replied and not is_auto:
        out_status = "Replied"
    elif not other_replied and days_since < 14:
        out_status = "Pending Reply"
    else:
        out_status = "No Contact"

    # Reason (human-readable)
    reasons = []
    if is_needs_reply:        reasons.append("they sent last — reply now")
    if has_interview:         reasons.append("interview/call discussed")
    if has_cv:                reasons.append("CV requested or submitted")
    if has_positive and not has_cv and not has_interview:
                              reasons.append("positive opportunity signal")
    if ghosted:               reasons.append(f"ghosted ({days_since}d ago)")
    if is_auto:               reasons.append("auto-reply only")
    if is_rejection:          reasons.append("rejection received")
    if is_dormant:            reasons.append("warm but dormant")
    if not reasons:           reasons.append("no notable signal")

    return score, out_status, "; ".join(reasons)


def compute_outreach_scores(threads_csv: Path = THREADS_CSV) -> dict:
    """
    Read message_threads_summary.csv and return per-URL outreach scoring dict.

    Returns:
        dict: {normalized_profile_url: {
            "outreach_adjusted_score": int,
            "outreach_status": str,
            "outreach_reason": str,
            "has_message_history": True,
            "replied_to_me": bool,
            "ghosted_me": bool,
            "auto_reply_only": bool,
            "last_message_date": str,
            "days_since_last_message": int,
            "prior_positive_signal": bool,
            "prior_rejection": bool,
        }}
    """
    if not threads_csv.exists():
        logger.info("  outreach scoring: message_threads_summary.csv not found — skipping")
        return {}

    try:
        df = pd.read_csv(threads_csv, dtype=str, low_memory=False, encoding="utf-8-sig")
    except Exception as exc:
        logger.warning(f"  outreach scoring: failed to read threads CSV: {exc}")
        return {}

    scores = {}

    for _, row in df.iterrows():
        url = _norm_url(row.get("other_person_profile_url", ""))
        if not url:
            continue

        base = float(row.get("connection_priority_score", 50) or 50)
        msgs_from_other = int(row.get("messages_from_other_person", 0) or 0)
        days_since_raw  = row.get("days_since_last_message", "")
        days_since      = int(days_since_raw) if str(days_since_raw).isdigit() else 9999

        adj_score, out_status, out_reason = _score_one(row.to_dict(), base)

        status     = str(row.get("conversation_status", "") or "")
        is_auto    = str(row.get("is_auto_reply", "False")).lower() == "true"
        has_pos    = str(row.get("has_positive_signal", "False")).lower() == "true"
        has_rej    = status == "Rejected / closed process"
        ghosted    = (
            str(row.get("last_sender", "")) == "me"
            and msgs_from_other == 0
            and days_since >= 14
        )

        scores[url] = {
            "outreach_adjusted_score":  adj_score,
            "outreach_status":          out_status,
            "outreach_reason":          out_reason,
            "has_message_history":      True,
            "replied_to_me":            msgs_from_other > 0,
            "ghosted_me":               ghosted,
            "auto_reply_only":          is_auto and msgs_from_other <= 1,
            "last_message_date":        str(row.get("last_message_date", "") or ""),
            "days_since_last_message":  days_since if days_since < 9999 else None,
            "prior_positive_signal":    has_pos,
            "prior_rejection":          has_rej,
        }

    logger.info(
        f"  outreach scoring: {len(scores):,} contacts scored | "
        f"ghosted={sum(1 for v in scores.values() if v['ghosted_me'])} | "
        f"replied={sum(1 for v in scores.values() if v['replied_to_me'])} | "
        f"interview_pipeline={sum(1 for v in scores.values() if v['outreach_status']=='Interview Pipeline')}"
    )
    return scores
